sudo: required
services:
   - docker

before_install:
   - docker build -t amitpandit09/DockerFileSamples -f Dockerfile.dev . 

script:
   - docker run amitpandit09/DockerFileSamples npm run test -- --coverage
